name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: true
      matrix:
        php: [ 8.0 ]
        stability: [ lowest, stable ]

    name: P${{ matrix.php }} - ${{ matrix.stability }}
    steps:

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          tools: composer:v2
          coverage: none

      - name: Install Composer dependencies
        run: composer update --prefer-dist --no-interaction --no-progress --prefer-${{ matrix.stability }}

      - name: Generate Application Key
        run: cp .env.example .env && php artisan key:generate

      - name: Run Test Suite
        run: php artisan test
        env:
          APP_URL: http://localhost
